apply:
		terraform apply --auto-approve
destroy:
		terraform destroy --auto-approve
docs:
		python -c "import subprocess; subprocess.run(['C:/Program Files/Git/bin/bash.exe','../scripts/generate_docs.sh'], check=True)"